variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
services:
  - docker:dind
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker info

stages:
  - build

build & push GitLab:
  image: docker:dind
  stage: build
  when: manual
  script:
    ## Build & push the deployer image to the registry
    - docker build -f $CI_PROJECT_DIR/Dockerfile -t $CI_REGISTRY/eit/development/saas/httpd-cas/httpd:latest . --no-cache
    - docker push $CI_REGISTRY/eit/development/saas/httpd-cas/httpd:latest

build & push GitHub:
  image: docker:dind
  stage: build
  when: manual
  before_script:
    - docker login -u engineeringit -p $DOCKER_HUB_TOKEN
  script:
    ## Build & push the deployer image to the registry
    - docker build -f $CI_PROJECT_DIR/Dockerfile -t $CI_REGISTRY/eit/development/saas/httpd-cas/httpd:latest . --no-cache
    - docker push httpdcas:latest
